import type { Metadata } from "next";
import AuthButton from "@/components/auth-button";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function WrappedLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <header className="p-10">
        <AuthButton />
      </header>
      <main className="h-full w-full flex justify-center items-center">
        {children}
      </main>
    </>
  );
}
